qualcommax: drop package qca-ssdk-shell
This one will not compile again latest master using kernel 6.6,
and it's not in the vanilla openwrt anyway.

```
2024-03-24T20:12:38.7478671Z fal_port_ctrl.c:216:1: error: conflicting types for 'fal_port_cdt' due to enum/integer mismatch; have 'sw_error_t(a_uint32_t,  fal_port_t,  a_uint32_t,  a_uint32_t *, a_uint32_t *)' {aka 'sw_error_t(unsigned int,  unsigned int,  unsigned int,  unsigned int *, unsigned int *)'} [-Werror=enum-int-mismatch]
2024-03-24T20:12:38.7481656Z   216 | fal_port_cdt(a_uint32_t dev_id, fal_port_t port_id, a_uint32_t mdi_pair,
2024-03-24T20:12:38.7482137Z       | ^~~~~~~~~~~~
2024-03-24T20:12:38.7482430Z In file included from fal_port_ctrl.c:21:
2024-03-24T20:12:38.7484444Z /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-ssdk-shell-2022.09.12~b43fba2d/include/fal/fal_port_ctrl.h:599:5: note: previous declaration of 'fal_port_cdt' with type 'sw_error_t(a_uint32_t,  fal_port_t,  a_uint32_t,  fal_cable_status_t *, a_uint32_t *)' {aka 'sw_error_t(unsigned int,  unsigned int,  unsigned int,  fal_cable_status_t *, unsigned int *)'}
2024-03-24T20:12:38.7486319Z   599 |     fal_port_cdt(a_uint32_t dev_id, fal_port_t port_id, a_uint32_t mdi_pair,
2024-03-24T20:12:38.7486786Z       |     ^~~~~~~~~~~~
2024-03-24T20:12:38.8694755Z cc1: all warnings being treated as errors
2024-03-24T20:12:38.8732680Z make[5]: *** [/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-ssdk-shell-2022.09.12~b43fba2d/make/target.mk:13: fal_port_ctrl.o] Error 1
2024-03-24T20:12:38.8734847Z make[5]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-ssdk-shell-2022.09.12~b43fba2d/src/fal_uk'
2024-03-24T20:12:38.8736336Z make[4]: *** [Makefile:28: uslib_o] Error 1
2024-03-24T20:12:38.8737682Z make[4]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-ssdk-shell-2022.09.12~b43fba2d'
2024-03-24T20:12:38.8739495Z make[3]: *** [Makefile:51: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-ssdk-shell-2022.09.12~b43fba2d/.built] Error 2
```

Therefore, propose to drop/remove this package, and anyone who really
need this can use community builds (that has out-of-tree NSS packages,
like ECM and WiFi offloading).