rockchip: fix rgb pinctrl dupelicate names
the last commit https://github.com/immortalwrt/immortalwrt/commit/bff07d91b61cc3e14c91bcfca4076611eae26ad2 introduce error/duplicate_node_names in dts file:

```
arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dts:548.33-550.5: ERROR (duplicate_node_names): /pinctrl/gpio-leds/status-led-pin: Duplicate node name
arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dts:552.32-554.5: ERROR (duplicate_node_names): /pinctrl/gpio-leds/status-led-pin: Duplicate node name
arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dts:552.32-554.5: ERROR (duplicate_node_names): /pinctrl/gpio-leds/status-led-pin: Duplicate node name
ERROR: Input tree has errors, aborting (use -f to force output)
make[8]: *** [scripts/Makefile.lib:423: arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dtb] Error 2
make[7]: *** [scripts/Makefile.build:480: arch/arm64/boot/dts/rockchip] Error 2
```

fix it via change the node names accordingly.