rtl8189es: bump to latest git HEAD
the current master fail to compile because mac80211 is already update to 6.1

```
  CC [M]  /workdir/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/rtl8812au-ct-2021-11-07-39df5596/os_dep/linux/ioctl_cfg80211.o
/workdir/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/rtl8812au-ct-2021-11-07-39df5596/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_cfg80211_indicate_connect':
/workdir/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/rtl8812au-ct-2021-11-07-39df5596/os_dep/linux/ioctl_cfg80211.c:801:26: error: 'struct cfg80211_roam_info' has no member named 'channel'
  801 |                 roam_info.channel = notify_channel;
      |                          ^
/workdir/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/rtl8812au-ct-2021-11-07-39df5596/os_dep/linux/ioctl_cfg80211.c:802:26: error: 'struct cfg80211_roam_info' has no member named 'bssid'
```

try to fix the compile using latest git (need test)